version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: the_angkor_times_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - directus_network

  minio:
    image: minio/minio:latest
    container_name: the_angkor_times_minio
    restart: always
    env_file:
      - .env
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/data
    networks:
      - directus_network

  directus:
    build: directus/directus:latest
    container_name: the_angkor_times_app
    restart: always
    ports:
      - "8055:8055"
    env_file:
      - .env
    depends_on:
      - postgres
      - minio
    networks:
      - directus_network

volumes:
  postgres_data:
  minio_data:

networks:
  directus_network:
    driver: bridge
